// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Supabase's Vercel integration exposes POSTGRES_PRISMA_URL (pooled,
    // pgbouncer-ready) rather than a plain DATABASE_URL.
    url: process.env["POSTGRES_PRISMA_URL"] ?? process.env["DATABASE_URL"],
  },
});
