// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Schema operations (db push, migrations) need a *direct* connection —
    // pgbouncer's pooled connection (POSTGRES_PRISMA_URL) can't run the
    // advisory locks the schema engine needs and just hangs instead of
    // failing. The Prisma Client at runtime (src/lib/prisma.ts) still uses
    // the pooled URL, which is correct for serverless.
    url:
      process.env["POSTGRES_URL_NON_POOLING"] ??
      process.env["DATABASE_URL"] ??
      process.env["POSTGRES_PRISMA_URL"],
  },
});
